services:
  db:
    image: postgres:latest
    container_name: social-postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - '5434:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: